13RC.yml

diff --git a/.github/workflows/13RC.yml b/.github/workflows/13RC.yml
--- a/.github/workflows/13RC.yml
+++ b/.github/workflows/13RC.yml
@@ -71,6 +71,19 @@ jobs:
           remove-haskell: 'true'
           remove-codeql: 'true'
 
+      - name: Validate Inputs
+        run: |
+          set -e
+          set -x
+          if [[ "${{ github.event.inputs.KERNEL_VERSION }}" != "6.1" && "${{ github.event.inputs.KERNEL_VERSION }}" != "6.6" ]]; then
+            echo "Error: KERNEL_VERSION must be 6.1 or 6.6"
+            exit 1
+          fi
+          if [[ "${{ github.event.inputs.ANDROID_VERSION }}" != "android14" ]]; then
+            echo "Error: ANDROID_VERSION must be android14"
+            exit 1
+          fi
+
       - name: Cache Clang Toolchain
         id: cache-clang
         uses: actions/cache@v4
@@ -99,7 +112,7 @@ jobs:
           git config --global user.name "OplusKernelBuilder"
           git config --global user.email "builder@opluskernel.org"
           repo --version > repo_version.log
-          
+
       - name: Initialize Repo and Sync
         run: |
           set -e
@@ -126,7 +139,12 @@ jobs:
           set -x
           cd kernel_workspace/kernel_platform/common
           chmod 644 arch/arm64/configs/gki_defconfig
+          if ! grep -q 'CONFIG_CMDLINE=' arch/arm64/configs/gki_defconfig; then
+            echo "Error: CONFIG_CMDLINE not found in gki_defconfig" > config_error.log
+            exit 1
+          fi
           sed -i 's/CONFIG_CMDLINE="\(.*\)"/CONFIG_CMDLINE="\1 module_blacklist=clk_gate_test,crypto_lz4p,ext4_inode_test,f_fs_ipc_log,gzvm,hung_task_enh,iio_test_format,kunit,kunit_example_test,kunit_test,oplus_bsp_sigkill_diagnosis,oplus_lock_torture,oplus_network_stats_calc,qcom_cpufreq_thermal,regmap_kunit,soc_topology_test,soc_utils_test"/' arch/arm64/configs/gki_defconfig
+
       - name: Clean Build Environment
         run: |
           set -e
@@ -150,7 +168,7 @@ jobs:
           KSU_VERSION=$(expr $(git rev-list --count main) + 10606)
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=[0-9]*/DKSU_VERSION=$KSU_VERSION/" kernel/Makefile
-          
+
       - name: Apply SUSFS Patches
         if: ${{ github.event.inputs.SUSFS_ENABLED == 'true' }}
         run: |
@@ -180,51 +198,59 @@ jobs:
           set -x
           cd kernel_workspace/kernel_platform
           CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
-          grep -q "^CONFIG_KSU=y" $CONFIG_FILE || echo "CONFIG_KSU=y" >> $CONFIG_FILE
+          cat << 'EOF' >> $CONFIG_FILE
+          CONFIG_KSU=y
+          CONFIG_KSU_SUSFS=y
+          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
+          CONFIG_KSU_SUSFS_SUS_PATH=y
+          CONFIG_KSU_SUSFS_SUS_MOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
+          CONFIG_KSU_SUSFS_SUS_KSTAT=y
+          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
+          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
+          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
+          CONFIG_KSU_SUSFS_ENABLE_LOG=y
+          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
+          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
+          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
+          CONFIG_KSU_SUSFS_SUS_SU=n
+          CONFIG_TMPFS_XATTR=y
+          CONFIG_TMPFS_POSIX_ACL=y
+          CONFIG_WIREGUARD=y
+          CONFIG_IP_NF_NAT=y
+          CONFIG_IP_NF_TARGET_TTL=y
+          CONFIG_IP6_NF_TARGET_HL=y
+          CONFIG_IP6_NF_MATCH_HL=y
+          CONFIG_DEBUG_KERNEL=n
+          CONFIG_DYNAMIC_DEBUG=n
+          CONFIG_DEBUG_INFO=n
+          CONFIG_TCP_CONG_ADVANCED=y
+          CONFIG_TCP_CONG_BBR=y
+          CONFIG_DEFAULT_TCP_CONG="bbr"
+          CONFIG_TCP_CONG_CDG=y
+          CONFIG_DEFAULT_BBR=y
+          CONFIG_DEFAULT_CUBIC=n
+          CONFIG_DEFAULT_CDG=n
+          CONFIG_NET_SCH_DEFAULT=y
+          CONFIG_DEFAULT_FQ=y
+          CONFIG_DEFAULT_NET_SCH="fq"
+          CONFIG_NET_SCH_HTB=y
+          CONFIG_NET_SCH_PRIO=y
+          CONFIG_NET_SCH_SFQ=y
+          CONFIG_NET_SCH_TBF=y
+          CONFIG_TCP_CONG_BIC=n
+          CONFIG_TCP_CONG_WESTWOOD=n
+          CONFIG_TCP_CONG_HTCP=y
+          CONFIG_IP_NF_TARGET_ECN=y
+          CONFIG_IP_ECN=y
+          CONFIG_TCP_ECN=y
+          CONFIG_IPV6_ECN=y
+          EOF
           if [[ "${{ github.event.inputs.kernelsu_variant }}" == "SukiSU-Ultra" ]]; then
             grep -q "^CONFIG_KPM=y" $CONFIG_FILE || echo "CONFIG_KPM=y" >> $CONFIG_FILE
           fi
-          grep -q "^CONFIG_KSU_SUSFS=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SUS_PATH=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SUS_MOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SUS_KSTAT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_TRY_UMOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SPOOF_UNAME=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_ENABLE_LOG=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_KSU_SUSFS_SUS_SU=n" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_TMPFS_XATTR=y" $CONFIG_FILE || echo "CONFIG_TMPFS_XATTR=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_TMPFS_POSIX_ACL=y" $CONFIG_FILE || echo "CONFIG_TMPFS_POSIX_ACL=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_WIREGUARD=y" $CONFIG_FILE || echo "CONFIG_WIREGUARD=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_IP_NF_NAT=y" $CONFIG_FILE || echo "CONFIG_IP_NF_NAT=y" >> $CONFIG
-          grep -q "^CONFIG_TCP_CONG_ADVANCED=y" $CONFIG_FILE || echo "CONFIG_TCP_CONG_ADVANCED=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_CONG_BBR=y" $CONFIG_FILE || echo "CONFIG_TCP_CONG_BBR=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_TCP_CONG=\"bbr\"" $CONFIG_FILE || echo "CONFIG_DEFAULT_TCP_CONG=\"bbr\"" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_CONG_CDG=y" $CONFIG_FILE || echo "CONFIG_TCP_CONG_CDG=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_BBR=y" $CONFIG_FILE || echo "CONFIG_DEFAULT_BBR=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_CUBIC=n" $CONFIG_FILE || echo "CONFIG_DEFAULT_CUBIC=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_CDG=n" $CONFIG_FILE || echo "CONFIG_DEFAULT_CDG=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_NET_SCH_DEFAULT=y" $CONFIG_FILE || echo "CONFIG_NET_SCH_DEFAULT=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_FQ=y" $CONFIG_FILE || echo "CONFIG_DEFAULT_FQ=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_DEFAULT_NET_SCH=\"fq\"" $CONFIG_FILE || echo "CONFIG_DEFAULT_NET_SCH=\"fq\"" >> $CONFIG_FILE
-          grep -q "^CONFIG_NET_SCH_HTB=y" $CONFIG_FILE || echo "CONFIG_NET_SCH_HTB=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_NET_SCH_PRIO=y" $CONFIG_FILE || echo "CONFIG_NET_SCH_PRIO=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_NET_SCH_SFQ=y" $CONFIG_FILE || echo "CONFIG_NET_SCH_SFQ=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_NET_SCH_TBF=y" $CONFIG_FILE || echo "CONFIG_NET_SCH_TBF=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_CONG_BIC=n" $CONFIG_FILE || echo "CONFIG_TCP_CONG_BIC=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_CONG_WESTWOOD=n" $CONFIG_FILE || echo "CONFIG_TCP_CONG_WESTWOOD=n" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_CONG_HTCP=y" $CONFIG_FILE || echo "CONFIG_TCP_CONG_HTCP=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_IP_NF_TARGET_ECN=y" $CONFIG_FILE || echo "CONFIG_IP_NF_TARGET_ECN=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_IP_ECN=y" $CONFIG_FILE || echo "CONFIG_IP_ECN=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_TCP_ECN=y" $CONFIG_FILE || echo "CONFIG_TCP_ECN=y" >> $CONFIG_FILE
-          grep -q "^CONFIG_IPV6_ECN=y" $CONFIG_FILE || echo "CONFIG_IPV6_ECN=y" >> $CONFIG_FILE
           sed -i 's/check_defconfig//' ./common/build.config.gki
 
       - name: Add Make Name
@@ -237,17 +263,27 @@ jobs:
           fi
           sed -i '$s|echo "\$res"|echo "\${{ github.event.inputs.KERNEL_NAME }}"|' common/scripts/setlocalversion
 
-      - name: sched
+      - name: Apply Scheduler Extensions
         run: |
           set -e
           set -x
           cd kernel_workspace
-            git clone https://github.com/cctv18/sched_ext.git
-            rm -rf ./sched_ext/.git
-            rm -rf ./sched_ext/README.md
-            cp -r ./sched_ext/* ./common/kernel/sched
+          git clone https://github.com/cctv18/sched_ext.git
+          rm -rf ./sched_ext/.git
+          rm -rf ./sched_ext/README.md
+          mkdir -p kernel_platform/common/kernel/sched
+          cp -r ./sched_ext/* ./kernel_platform/common/kernel/sched
+
+      - name: Log Kernel Configuration
+        run: |
+          set -e
+          set -x
+          cd kernel_workspace/kernel_platform/common
+          grep "CONFIG_CMDLINE" arch/arm64/configs/gki_defconfig > config_cmdline.log || echo "CONFIG_CMDLINE not found" > config_cmdline.log
+          grep -E "^CONFIG_(KSU|KPM|KSU_SUSFS)" arch/arm64/configs/gki_defconfig > config_susfs.log || echo "No KSU/SUSFS configs found" > config_susfs.log
 
       - name: Build Kernel
+        timeout-minutes: 60
         run: |
           set -e
           set -x
@@ -280,10 +316,10 @@ jobs:
           cd AnyKernel3-kpm && zip -r ../AnyKernel3-kpm_${{ env.KSUVER }}_13r.zip . && cd ..
 
       - name: Upload Artifacts
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: kernel-artifacts
           path: |
             kernel_workspace/kernel_platform/dist/AnyKernel3-no_kpm_${{ env.KSUVER }}_13r.zip
             kernel_workspace/kernel_platform/dist/AnyKernel3-kpm_${{ env.KSUVER }}_13r.zip
-
